# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yangweigbh
email: yangweigbh@hotmail.com
description: my blog about algorithm and computer science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/yangweigbh/" # the base hostname & protocol for your site
twitter_username: yangweigbh
github_username:  yangweigbh

# Build settings
#markdown: kramdown
input: GFM
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
